### ISSUE TITLE
Не работает фильтрация IsInList если фильтруемое поле находится в группе

### ISSUE THREAD

**Issue by ifugene** [simplygoodsoftware/pyrusapi-csharp#37]
## Expected Behavior
Должен возвращаться отфильтрованный список задач по форме.

## Current Behavior
Срабатывает ArgumentException: "Field with specified name not found on the form.".

## Possible Solution
В PyrusApiClient.FormFilter.GetFieldIdByName искать поле на всех уровнях иерархии полей.

## Detailed Description
Если поле fieldName имеет родительское поле (находится в группе), то поле не может быть найдено по имени.
_Если вместо fieldName подавать id поля, то исключение не срабатывает, но задачи не находятся (FormRegisterResponse.Tasks = null)_

## Steps to Reproduce
1. Создать на форме текстовое поле fieldName со значением 1 и поместить его в группу 
2. Выполнить:
var objectsListFilter = new List<object>() { "1" };
var response = await RequestBuilder
    .GetRegistry(formId)
    .IncludingArchived()
    .FilteredBy
    **.Field(fieldName).IsInList(objectsListFilter)**
    .Process(PyrusClient);

**Comment by dkuptsov** [comment]
@ifugene, добрый день, ошибка исправлена в версии 2.2.38.1.
