### ISSUE TITLE
Возможность использовать свой экземпляр HttpClient

### ISSUE THREAD

**Issue by Vanwards** [simplygoodsoftware/pyrusapi-csharp#68]
Добрый день,

Для логгирования мы используем свою реализацию `HttpClientFactory` и появилась необходимость подстановки `HttpClient`. Для этого можно сделать возможность переопределять метод создания `NewHttpClient`.

Ожидаемый результат:
```csharp
public class CustomSettings : Settings
{
    private readonly HttpClient _httpClient;

    public CustomSettings(HttpClient httpClient)
    {
        _httpClient = httpClient;
    }

    public override HttpClient NewHttpClient(TimeSpan timeout)
    {
        _httpClient.Timeout = timeout;

       return _httpClient;
    }
}

_pyrusClient = new PyrusClient(new CustomSettings(httpClient));
```

Сделал PR#65

**Comment by dkuptsov** [comment]
Hello! Thank you for your contribution to improving the library. These changes were released in version 3.0.4.0.
